/**
 * This app's sealed transport against cide's own, byte for byte.
 *
 * `src/crypto/seal.ts` is a second implementation of `crates/cide-remote/src/seal.rs`, and every
 * way the two can disagree is silent: a wrong HKDF label, a byte order, a transposed direction —
 * each derives a perfectly good channel the other end cannot read, and the symptom is a socket
 * that opens and then goes quiet, which is what a bad network looks like too.
 *
 * So the ground truth is generated by the Rust (`cargo test -p cide-remote --test vectors --
 * --ignored`) and copied here. What is asserted is not "these produce similar output" but the
 * two things that matter:
 *
 *  * this code **opens** frames the Rust sealed, in both directions;
 *  * this code **seals** frames the Rust produced, to the same bytes — which is the stronger
 *    half, because it pins the nonce and the counter and not merely the key.
 */
import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  Channel,
  Mode,
  SEAL_VERSION,
  deriveChannel,
  encodeHandshake,
  fromHex,
  type Handshake,
} from '../src/crypto/seal'

const here = dirname(fileURLToPath(import.meta.url))

interface Frame {
  plaintext: string
  sealed: string
}

interface Case {
  mode: 'pair' | 'resume'
  device: string
  psk: string
  serverStaticPublic: string
  clientEphemeralSecret: string
  clientEphemeralPublic: string
  handshake: string
  sas: string
  clientToServer: Frame[]
  serverToClient: Frame[]
}

const vectors = JSON.parse(readFileSync(join(here, 'seal-vectors.json'), 'utf8')) as {
  sealVersion: number
  cases: Case[]
}

const text = new TextEncoder()
const hex = (bytes: Uint8Array) =>
  [...bytes].map((b) => b.toString(16).padStart(2, '0')).join('')

function channelFor(c: Case): { channel: Channel; handshake: Handshake } {
  const handshake: Handshake = {
    mode: c.mode === 'pair' ? Mode.Pair : Mode.Resume,
    ephemeral: fromHex(c.clientEphemeralPublic),
    device: c.device,
  }
  const channel = deriveChannel(
    fromHex(c.clientEphemeralSecret),
    fromHex(c.serverStaticPublic),
    handshake,
    fromHex(c.psk),
  )
  return { channel, handshake }
}

describe('the sealed transport agrees with cide', () => {
  it('records the seal version this code implements', () => {
    expect(vectors.sealVersion).toBe(SEAL_VERSION)
  })

  it('has vectors for pairing and for resuming', () => {
    expect(vectors.cases.map((c) => c.mode)).toContain('pair')
    expect(vectors.cases.map((c) => c.mode)).toContain('resume')
  })

  for (const [index, c] of vectors.cases.entries()) {
    describe(`case ${index} (${c.mode})`, () => {
      it('derives the same six digits cide derived', () => {
        // The typed pairing road rests entirely on two *different implementations* reaching
        // the same number from the same exchange. A divergence would break no connection and
        // fail nothing else here — it would show two numbers to a person, who would correctly
        // conclude they were being attacked and stop. That is why it is a pinned vector and
        // not a property test.
        expect(channelFor(c).channel.sas).toBe(c.sas)
        expect(c.sas).toMatch(/^[0-9]{6}$/)
      })

      it('encodes the handshake to the same bytes', () => {
        const { handshake } = channelFor(c)
        expect(hex(encodeHandshake(handshake))).toBe(c.handshake)
      })

      it('seals to exactly what cide sealed', () => {
        // The stronger half. Opening only pins the key; sealing pins the nonce prefix, the
        // counter, and that the counter is authenticated rather than merely sent.
        const { channel } = channelFor(c)
        for (const frame of c.clientToServer) {
          expect(hex(channel.seal(text.encode(frame.plaintext)))).toBe(frame.sealed)
        }
      })

      it("opens what cide's server sealed", () => {
        const { channel } = channelFor(c)
        const decoder = new TextDecoder()
        for (const frame of c.serverToClient) {
          expect(decoder.decode(channel.open(fromHex(frame.sealed)))).toBe(frame.plaintext)
        }
      })

      it('refuses a frame that arrived out of order', () => {
        const { channel } = channelFor(c)
        const [, second] = c.serverToClient
        expect(second).toBeDefined()
        // The second frame first: exact succession, not mere increase.
        expect(() => channel.open(fromHex(second!.sealed))).toThrow(/out of order/)
      })

      it('refuses a tampered frame', () => {
        const { channel } = channelFor(c)
        const first = c.serverToClient[0]!
        const bytes = fromHex(first.sealed)
        // `noUncheckedIndexedAccess` is on, and it is right to be: the last byte of a frame is
        // only defined because a sealed frame is never empty, which is a fact about the vectors
        // rather than about the type.
        const last = bytes.length - 1
        bytes[last] = (bytes[last] ?? 0) ^ 1
        expect(() => channel.open(bytes)).toThrow()
      })

      it('refuses a frame sealed under a different key', () => {
        const wrong = deriveChannel(
          fromHex(c.clientEphemeralSecret),
          fromHex(c.serverStaticPublic),
          {
            mode: c.mode === 'pair' ? Mode.Pair : Mode.Resume,
            ephemeral: fromHex(c.clientEphemeralPublic),
            device: c.device,
          },
          // One byte different is enough, and it must be enough.
          fromHex(c.psk.length > 0 ? `ff${c.psk.slice(2)}` : 'ff'),
        )
        expect(() => wrong.open(fromHex(c.serverToClient[0]!.sealed))).toThrow()
      })
    })
  }
})

describe('UTF-8 without the platform', () => {
  it('agrees with TextEncoder on everything, including what is malformed', async () => {
    const { decodeUtf8, encodeUtf8 } = await import('../src/crypto/utf8')
    const encoder = new TextEncoder()
    const decoder = new TextDecoder()

    for (const text of [
      '',
      'hello',
      'claude',
      '[DEV] thinkpad',
      'é accented',
      '日本語のテキスト',
      '😀😀 emoji and 🏳️‍🌈 a sequence',
      'mixed 日本 😀 ascii',
      '\u0000control\u001b[0m',
      // A lone surrogate, which `TextEncoder` turns into U+FFFD rather than refusing — and so
      // must this, because a device name is not the place to discover it.
      'broken \ud800 half',
    ]) {
      expect([...encodeUtf8(text)], text).toEqual([...encoder.encode(text)])
      expect(decodeUtf8(encodeUtf8(text)), text).toBe(decoder.decode(encoder.encode(text)))
    }
  })

  it('round-trips every byte length of random data as bytes', async () => {
    const { decodeUtf8, encodeUtf8 } = await import('../src/crypto/utf8')
    for (let i = 0; i < 64; i++) {
      const text = 'x'.repeat(i)
      expect(decodeUtf8(encodeUtf8(text))).toBe(text)
    }
  })

  it('does not throw on truncated or invalid input', async () => {
    const { decodeUtf8 } = await import('../src/crypto/utf8')
    // A frame that fails to authenticate can still be handed to a decoder by mistake; it must
    // produce a string, not an exception in a socket handler.
    expect(() => decodeUtf8(new Uint8Array([0xe6, 0x97]))).not.toThrow()
    expect(() => decodeUtf8(new Uint8Array([0xff, 0xfe, 0x80]))).not.toThrow()
    expect(decodeUtf8(new Uint8Array([0x41, 0xff, 0x42]))).toContain('A')
  })
})

describe('the random source', () => {
  it('is injectable, and names its absence rather than failing three libraries down', async () => {
    const { installRandom, randomBytes } = await import('../src/crypto/random')
    // Hermes has no `crypto.getRandomValues`, so this is not a hypothetical: without an
    // injected source the failure is an `undefined is not a function` from inside noble.
    installRandom((n) => new Uint8Array(n).fill(7))
    expect([...randomBytes(4)]).toEqual([7, 7, 7, 7])
    installRandom((n) => (globalThis.crypto as Crypto).getRandomValues(new Uint8Array(n)))
    expect(randomBytes(32)).toHaveLength(32)
  })
})
